
language: python
python:
  - "3.6"

# command to install dependencies

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage
  - pip install codeclimate-test-reporter
  - pip install pytest
  - pip install pytest-cov

# command to run tests
script:
  - pytest
  - pytest --cov

after_success:
  - coveralls
  - coverage xml
  - codeclimate-test-reporter
